module PreludeSDK
  module Models
    module Verification
      module Phone
        type history_retrieve_response =
          {
            id: String,
            created_at: Time,
            expires_at: Time,
            phone_number: String,
            status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::status,
            app_version: String,
            block_reasons: ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::block_reason],
            carrier: PreludeSDK::Verification::Phone::PhoneVerificationCarrier,
            correlation_id: String,
            device_model: String,
            device_platform: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::device_platform,
            ip_address: String,
            ip_address_region: String,
            ip_distance_meters: Integer,
            lifecycle: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle,
            phone_number_condition: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_condition,
            phone_number_current_condition: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_current_condition,
            phone_number_region: String,
            signals: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Signals,
            signals_hash_status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::signals_hash_status,
            template_id: String
          }

        class HistoryRetrieveResponse < PreludeSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor created_at: Time

          attr_accessor expires_at: Time

          attr_accessor phone_number: String

          attr_accessor status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::status

          attr_reader app_version: String?

          def app_version=: (String) -> String

          attr_reader block_reasons: ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::block_reason]?

          def block_reasons=: (
            ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::block_reason]
          ) -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::block_reason]

          attr_reader carrier: PreludeSDK::Verification::Phone::PhoneVerificationCarrier?

          def carrier=: (
            PreludeSDK::Verification::Phone::PhoneVerificationCarrier
          ) -> PreludeSDK::Verification::Phone::PhoneVerificationCarrier

          attr_reader correlation_id: String?

          def correlation_id=: (String) -> String

          attr_reader device_model: String?

          def device_model=: (String) -> String

          attr_reader device_platform: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::device_platform?

          def device_platform=: (
            PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::device_platform
          ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::device_platform

          attr_reader ip_address: String?

          def ip_address=: (String) -> String

          attr_reader ip_address_region: String?

          def ip_address_region=: (String) -> String

          attr_reader ip_distance_meters: Integer?

          def ip_distance_meters=: (Integer) -> Integer

          attr_reader lifecycle: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle?

          def lifecycle=: (
            PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle
          ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle

          attr_reader phone_number_condition: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_condition?

          def phone_number_condition=: (
            PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_condition
          ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_condition

          attr_reader phone_number_current_condition: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_current_condition?

          def phone_number_current_condition=: (
            PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_current_condition
          ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_current_condition

          attr_reader phone_number_region: String?

          def phone_number_region=: (String) -> String

          attr_reader signals: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Signals?

          def signals=: (
            PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Signals
          ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Signals

          attr_reader signals_hash_status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::signals_hash_status?

          def signals_hash_status=: (
            PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::signals_hash_status
          ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::signals_hash_status

          attr_reader template_id: String?

          def template_id=: (String) -> String

          def initialize: (
            id: String,
            created_at: Time,
            expires_at: Time,
            phone_number: String,
            status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::status,
            ?app_version: String,
            ?block_reasons: ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::block_reason],
            ?carrier: PreludeSDK::Verification::Phone::PhoneVerificationCarrier,
            ?correlation_id: String,
            ?device_model: String,
            ?device_platform: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::device_platform,
            ?ip_address: String,
            ?ip_address_region: String,
            ?ip_distance_meters: Integer,
            ?lifecycle: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle,
            ?phone_number_condition: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_condition,
            ?phone_number_current_condition: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_current_condition,
            ?phone_number_region: String,
            ?signals: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Signals,
            ?signals_hash_status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::signals_hash_status,
            ?template_id: String
          ) -> void

          def to_hash: -> {
            id: String,
            created_at: Time,
            expires_at: Time,
            phone_number: String,
            status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::status,
            app_version: String,
            block_reasons: ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::block_reason],
            carrier: PreludeSDK::Verification::Phone::PhoneVerificationCarrier,
            correlation_id: String,
            device_model: String,
            device_platform: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::device_platform,
            ip_address: String,
            ip_address_region: String,
            ip_distance_meters: Integer,
            lifecycle: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle,
            phone_number_condition: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_condition,
            phone_number_current_condition: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_current_condition,
            phone_number_region: String,
            signals: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Signals,
            signals_hash_status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::signals_hash_status,
            template_id: String
          }

          type status =
            :converted
            | :not_converted
            | :pending_check
            | :sent
            | :challenged
            | :suspected_fraud
            | :in_blocklist
            | :invalid_line
            | :invalid_number
            | :rate_limited
            | :expired_signals
            | :shadowed

          module Status
            extend PreludeSDK::Internal::Type::Enum

            CONVERTED: :converted
            NOT_CONVERTED: :not_converted
            PENDING_CHECK: :pending_check
            SENT: :sent
            CHALLENGED: :challenged
            SUSPECTED_FRAUD: :suspected_fraud
            IN_BLOCKLIST: :in_blocklist
            INVALID_LINE: :invalid_line
            INVALID_NUMBER: :invalid_number
            RATE_LIMITED: :rate_limited
            EXPIRED_SIGNALS: :expired_signals
            SHADOWED: :shadowed

            def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::status]
          end

          type block_reason =
            :automation_signature
            | :carrier_not_permitted
            | :client_fingerprint_mismatch
            | :custom_policy
            | :device_emulator
            | :device_not_permitted
            | :device_reuse
            | :expired_signals
            | :fraud_database
            | :invalid_signature
            | :ip_concentration
            | :ip_reputation
            | :location_mismatch
            | :missing_signals
            | :number_range_abuse
            | :poor_conversion_history
            | :proxy_network
            | :repeated_attempts
            | :temporary_phone_number

          module BlockReason
            extend PreludeSDK::Internal::Type::Enum

            AUTOMATION_SIGNATURE: :automation_signature
            CARRIER_NOT_PERMITTED: :carrier_not_permitted
            CLIENT_FINGERPRINT_MISMATCH: :client_fingerprint_mismatch
            CUSTOM_POLICY: :custom_policy
            DEVICE_EMULATOR: :device_emulator
            DEVICE_NOT_PERMITTED: :device_not_permitted
            DEVICE_REUSE: :device_reuse
            EXPIRED_SIGNALS: :expired_signals
            FRAUD_DATABASE: :fraud_database
            INVALID_SIGNATURE: :invalid_signature
            IP_CONCENTRATION: :ip_concentration
            IP_REPUTATION: :ip_reputation
            LOCATION_MISMATCH: :location_mismatch
            MISSING_SIGNALS: :missing_signals
            NUMBER_RANGE_ABUSE: :number_range_abuse
            POOR_CONVERSION_HISTORY: :poor_conversion_history
            PROXY_NETWORK: :proxy_network
            REPEATED_ATTEMPTS: :repeated_attempts
            TEMPORARY_PHONE_NUMBER: :temporary_phone_number

            def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::block_reason]
          end

          type device_platform = :android | :ios | :ipados | :tvos | :web

          module DevicePlatform
            extend PreludeSDK::Internal::Type::Enum

            ANDROID: :android
            IOS: :ios
            IPADOS: :ipados
            TVOS: :tvos
            WEB: :web

            def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::device_platform]
          end

          type lifecycle =
            {
              events: ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event],
              total_cost: PreludeSDK::Verification::Phone::PhoneVerificationMoney,
              undeliverable_route_count: Integer
            }

          class Lifecycle < PreludeSDK::Internal::Type::BaseModel
            attr_accessor events: ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event]

            attr_reader total_cost: PreludeSDK::Verification::Phone::PhoneVerificationMoney?

            def total_cost=: (
              PreludeSDK::Verification::Phone::PhoneVerificationMoney
            ) -> PreludeSDK::Verification::Phone::PhoneVerificationMoney

            attr_reader undeliverable_route_count: Integer?

            def undeliverable_route_count=: (Integer) -> Integer

            def initialize: (
              events: ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event],
              ?total_cost: PreludeSDK::Verification::Phone::PhoneVerificationMoney,
              ?undeliverable_route_count: Integer
            ) -> void

            def to_hash: -> {
              events: ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event],
              total_cost: PreludeSDK::Verification::Phone::PhoneVerificationMoney,
              undeliverable_route_count: Integer
            }

            type event =
              {
                type: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::type_,
                attempt: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt,
                check: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check,
                create: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Create,
                signals: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Signals
              }

            class Event < PreludeSDK::Internal::Type::BaseModel
              attr_accessor type: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::type_

              attr_reader attempt: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt?

              def attempt=: (
                PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt
              ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt

              attr_reader check: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check?

              def check=: (
                PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check
              ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check

              attr_reader create: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Create?

              def create=: (
                PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Create
              ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Create

              attr_reader signals: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Signals?

              def signals=: (
                PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Signals
              ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Signals

              def initialize: (
                type: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::type_,
                ?attempt: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt,
                ?check: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check,
                ?create: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Create,
                ?signals: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Signals
              ) -> void

              def to_hash: -> {
                type: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::type_,
                attempt: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt,
                check: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check,
                create: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Create,
                signals: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Signals
              }

              type type_ = :create | :attempt | :check | :signals

              module Type
                extend PreludeSDK::Internal::Type::Enum

                CREATE: :create
                ATTEMPT: :attempt
                CHECK: :check
                SIGNALS: :signals

                def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::type_]
              end

              type attempt =
                {
                  id: String,
                  created_at: Time,
                  carrier: PreludeSDK::Verification::Phone::PhoneVerificationCarrier,
                  channel: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::channel,
                  content: String,
                  cost: PreludeSDK::Verification::Phone::PhoneVerificationMoney,
                  delivery_events: ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::DeliveryEvent],
                  delivery_status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::delivery_status,
                  preferred_channel: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::preferred_channel,
                  status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::status,
                  trigger: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::trigger
                }

              class Attempt < PreludeSDK::Internal::Type::BaseModel
                attr_accessor id: String

                attr_accessor created_at: Time

                attr_reader carrier: PreludeSDK::Verification::Phone::PhoneVerificationCarrier?

                def carrier=: (
                  PreludeSDK::Verification::Phone::PhoneVerificationCarrier
                ) -> PreludeSDK::Verification::Phone::PhoneVerificationCarrier

                attr_reader channel: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::channel?

                def channel=: (
                  PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::channel
                ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::channel

                attr_reader content: String?

                def content=: (String) -> String

                attr_reader cost: PreludeSDK::Verification::Phone::PhoneVerificationMoney?

                def cost=: (
                  PreludeSDK::Verification::Phone::PhoneVerificationMoney
                ) -> PreludeSDK::Verification::Phone::PhoneVerificationMoney

                attr_reader delivery_events: ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::DeliveryEvent]?

                def delivery_events=: (
                  ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::DeliveryEvent]
                ) -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::DeliveryEvent]

                attr_reader delivery_status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::delivery_status?

                def delivery_status=: (
                  PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::delivery_status
                ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::delivery_status

                attr_reader preferred_channel: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::preferred_channel?

                def preferred_channel=: (
                  PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::preferred_channel
                ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::preferred_channel

                attr_reader status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::status?

                def status=: (
                  PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::status
                ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::status

                attr_reader trigger: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::trigger?

                def trigger=: (
                  PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::trigger
                ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::trigger

                def initialize: (
                  id: String,
                  created_at: Time,
                  ?carrier: PreludeSDK::Verification::Phone::PhoneVerificationCarrier,
                  ?channel: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::channel,
                  ?content: String,
                  ?cost: PreludeSDK::Verification::Phone::PhoneVerificationMoney,
                  ?delivery_events: ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::DeliveryEvent],
                  ?delivery_status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::delivery_status,
                  ?preferred_channel: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::preferred_channel,
                  ?status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::status,
                  ?trigger: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::trigger
                ) -> void

                def to_hash: -> {
                  id: String,
                  created_at: Time,
                  carrier: PreludeSDK::Verification::Phone::PhoneVerificationCarrier,
                  channel: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::channel,
                  content: String,
                  cost: PreludeSDK::Verification::Phone::PhoneVerificationMoney,
                  delivery_events: ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::DeliveryEvent],
                  delivery_status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::delivery_status,
                  preferred_channel: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::preferred_channel,
                  status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::status,
                  trigger: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::trigger
                }

                type channel =
                  :sms
                  | :rcs
                  | :whatsapp
                  | :viber
                  | :zalo
                  | :telegram
                  | :voice
                  | :silent

                module Channel
                  extend PreludeSDK::Internal::Type::Enum

                  SMS: :sms
                  RCS: :rcs
                  WHATSAPP: :whatsapp
                  VIBER: :viber
                  ZALO: :zalo
                  TELEGRAM: :telegram
                  VOICE: :voice
                  SILENT: :silent

                  def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::channel]
                end

                type delivery_event =
                  {
                    received_at: Time,
                    status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::DeliveryEvent::status
                  }

                class DeliveryEvent < PreludeSDK::Internal::Type::BaseModel
                  attr_accessor received_at: Time

                  attr_accessor status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::DeliveryEvent::status

                  def initialize: (
                    received_at: Time,
                    status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::DeliveryEvent::status
                  ) -> void

                  def to_hash: -> {
                    received_at: Time,
                    status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::DeliveryEvent::status
                  }

                  type status =
                    :unknown
                    | :submitted
                    | :in_transit
                    | :delivered
                    | :undeliverable
                    | :expired
                    | :read
                    | :silent_started
                    | :silent_verified
                    | :silent_mismatch

                  module Status
                    extend PreludeSDK::Internal::Type::Enum

                    UNKNOWN: :unknown
                    SUBMITTED: :submitted
                    IN_TRANSIT: :in_transit
                    DELIVERED: :delivered
                    UNDELIVERABLE: :undeliverable
                    EXPIRED: :expired
                    READ: :read
                    SILENT_STARTED: :silent_started
                    SILENT_VERIFIED: :silent_verified
                    SILENT_MISMATCH: :silent_mismatch

                    def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::DeliveryEvent::status]
                  end
                end

                type delivery_status =
                  :unknown | :in_transit | :delivered | :undeliverable | :read

                module DeliveryStatus
                  extend PreludeSDK::Internal::Type::Enum

                  UNKNOWN: :unknown
                  IN_TRANSIT: :in_transit
                  DELIVERED: :delivered
                  UNDELIVERABLE: :undeliverable
                  READ: :read

                  def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::delivery_status]
                end

                type preferred_channel =
                  :sms
                  | :rcs
                  | :whatsapp
                  | :viber
                  | :zalo
                  | :telegram
                  | :voice
                  | :silent

                module PreferredChannel
                  extend PreludeSDK::Internal::Type::Enum

                  SMS: :sms
                  RCS: :rcs
                  WHATSAPP: :whatsapp
                  VIBER: :viber
                  ZALO: :zalo
                  TELEGRAM: :telegram
                  VOICE: :voice
                  SILENT: :silent

                  def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::preferred_channel]
                end

                type status = :succeeded | :failed

                module Status
                  extend PreludeSDK::Internal::Type::Enum

                  SUCCEEDED: :succeeded
                  FAILED: :failed

                  def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::status]
                end

                type trigger = :initial | :auto_retry | :user_retry

                module Trigger
                  extend PreludeSDK::Internal::Type::Enum

                  INITIAL: :initial
                  AUTO_RETRY: :auto_retry
                  USER_RETRY: :user_retry

                  def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Attempt::trigger]
                end
              end

              type check =
                {
                  created_at: Time,
                  is_valid: bool,
                  channel: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::channel,
                  :psd2_info => PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::Psd2Info,
                  status_detail: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::status_detail,
                  value: String
                }

              class Check < PreludeSDK::Internal::Type::BaseModel
                attr_accessor created_at: Time

                attr_accessor is_valid: bool

                attr_reader channel: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::channel?

                def channel=: (
                  PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::channel
                ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::channel

                attr_reader psd2_info: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::Psd2Info?

                def psd2_info=: (
                  PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::Psd2Info
                ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::Psd2Info

                attr_reader status_detail: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::status_detail?

                def status_detail=: (
                  PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::status_detail
                ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::status_detail

                attr_reader value: String?

                def value=: (String) -> String

                def initialize: (
                  created_at: Time,
                  is_valid: bool,
                  ?channel: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::channel,
                  ?psd2_info: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::Psd2Info,
                  ?status_detail: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::status_detail,
                  ?value: String
                ) -> void

                def to_hash: -> {
                  created_at: Time,
                  is_valid: bool,
                  channel: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::channel,
                  :psd2_info => PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::Psd2Info,
                  status_detail: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::status_detail,
                  value: String
                }

                type channel =
                  :sms
                  | :rcs
                  | :whatsapp
                  | :viber
                  | :zalo
                  | :telegram
                  | :voice
                  | :silent

                module Channel
                  extend PreludeSDK::Internal::Type::Enum

                  SMS: :sms
                  RCS: :rcs
                  WHATSAPP: :whatsapp
                  VIBER: :viber
                  ZALO: :zalo
                  TELEGRAM: :telegram
                  VOICE: :voice
                  SILENT: :silent

                  def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::channel]
                end

                type psd2_info =
                  {
                    expected_transaction: PreludeSDK::Verification::Phone::PhoneVerificationPsd2Transaction,
                    received_transaction: PreludeSDK::Verification::Phone::PhoneVerificationPsd2Transaction
                  }

                class Psd2Info < PreludeSDK::Internal::Type::BaseModel
                  attr_reader expected_transaction: PreludeSDK::Verification::Phone::PhoneVerificationPsd2Transaction?

                  def expected_transaction=: (
                    PreludeSDK::Verification::Phone::PhoneVerificationPsd2Transaction
                  ) -> PreludeSDK::Verification::Phone::PhoneVerificationPsd2Transaction

                  attr_reader received_transaction: PreludeSDK::Verification::Phone::PhoneVerificationPsd2Transaction?

                  def received_transaction=: (
                    PreludeSDK::Verification::Phone::PhoneVerificationPsd2Transaction
                  ) -> PreludeSDK::Verification::Phone::PhoneVerificationPsd2Transaction

                  def initialize: (
                    ?expected_transaction: PreludeSDK::Verification::Phone::PhoneVerificationPsd2Transaction,
                    ?received_transaction: PreludeSDK::Verification::Phone::PhoneVerificationPsd2Transaction
                  ) -> void

                  def to_hash: -> {
                    expected_transaction: PreludeSDK::Verification::Phone::PhoneVerificationPsd2Transaction,
                    received_transaction: PreludeSDK::Verification::Phone::PhoneVerificationPsd2Transaction
                  }
                end

                type status_detail =
                  :expired_attempt
                  | :expired_auth
                  | :rate_limited
                  | :transaction_missing
                  | :transaction_mismatch

                module StatusDetail
                  extend PreludeSDK::Internal::Type::Enum

                  EXPIRED_ATTEMPT: :expired_attempt
                  EXPIRED_AUTH: :expired_auth
                  RATE_LIMITED: :rate_limited
                  TRANSACTION_MISSING: :transaction_missing
                  TRANSACTION_MISMATCH: :transaction_mismatch

                  def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Check::status_detail]
                end
              end

              type create =
                {
                  created_at: Time,
                  cost: PreludeSDK::Verification::Phone::PhoneVerificationMoney
                }

              class Create < PreludeSDK::Internal::Type::BaseModel
                attr_accessor created_at: Time

                attr_reader cost: PreludeSDK::Verification::Phone::PhoneVerificationMoney?

                def cost=: (
                  PreludeSDK::Verification::Phone::PhoneVerificationMoney
                ) -> PreludeSDK::Verification::Phone::PhoneVerificationMoney

                def initialize: (
                  created_at: Time,
                  ?cost: PreludeSDK::Verification::Phone::PhoneVerificationMoney
                ) -> void

                def to_hash: -> {
                  created_at: Time,
                  cost: PreludeSDK::Verification::Phone::PhoneVerificationMoney
                }
              end

              type signals =
                {
                  received_at: Time,
                  expired_at: Time,
                  status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Signals::status
                }

              class Signals < PreludeSDK::Internal::Type::BaseModel
                attr_accessor received_at: Time

                attr_reader expired_at: Time?

                def expired_at=: (Time) -> Time

                attr_reader status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Signals::status?

                def status=: (
                  PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Signals::status
                ) -> PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Signals::status

                def initialize: (
                  received_at: Time,
                  ?expired_at: Time,
                  ?status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Signals::status
                ) -> void

                def to_hash: -> {
                  received_at: Time,
                  expired_at: Time,
                  status: PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Signals::status
                }

                type status = :valid | :invalid

                module Status
                  extend PreludeSDK::Internal::Type::Enum

                  VALID: :valid
                  INVALID: :invalid

                  def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::Lifecycle::Event::Signals::status]
                end
              end
            end
          end

          type phone_number_condition =
            :allow_listed | :block_listed | :sandboxed

          module PhoneNumberCondition
            extend PreludeSDK::Internal::Type::Enum

            ALLOW_LISTED: :allow_listed
            BLOCK_LISTED: :block_listed
            SANDBOXED: :sandboxed

            def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_condition]
          end

          type phone_number_current_condition =
            :allow_listed | :block_listed | :sandboxed

          module PhoneNumberCurrentCondition
            extend PreludeSDK::Internal::Type::Enum

            ALLOW_LISTED: :allow_listed
            BLOCK_LISTED: :block_listed
            SANDBOXED: :sandboxed

            def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::phone_number_current_condition]
          end

          type signals =
            {
              is_trusted_user: bool,
              device_id: String,
              :ja4_fingerprint => String,
              os_version: String,
              user_agent: String
            }

          class Signals < PreludeSDK::Internal::Type::BaseModel
            attr_accessor is_trusted_user: bool

            attr_reader device_id: String?

            def device_id=: (String) -> String

            attr_reader ja4_fingerprint: String?

            def ja4_fingerprint=: (String) -> String

            attr_reader os_version: String?

            def os_version=: (String) -> String

            attr_reader user_agent: String?

            def user_agent=: (String) -> String

            def initialize: (
              is_trusted_user: bool,
              ?device_id: String,
              ?ja4_fingerprint: String,
              ?os_version: String,
              ?user_agent: String
            ) -> void

            def to_hash: -> {
              is_trusted_user: bool,
              device_id: String,
              :ja4_fingerprint => String,
              os_version: String,
              user_agent: String
            }
          end

          type signals_hash_status = :valid | :invalid

          module SignalsHashStatus
            extend PreludeSDK::Internal::Type::Enum

            VALID: :valid
            INVALID: :invalid

            def self?.values: -> ::Array[PreludeSDK::Models::Verification::Phone::HistoryRetrieveResponse::signals_hash_status]
          end
        end
      end
    end
  end
end
