module PreludeSDK
  module Resources
    class VerificationManagement
      def list_sender_ids: (
        ?request_options: PreludeSDK::request_opts
      ) -> PreludeSDK::Models::VerificationManagementListSenderIDsResponse

      def submit_sender_id: (
        sender_id: String,
        ?request_options: PreludeSDK::request_opts
      ) -> PreludeSDK::Models::VerificationManagementSubmitSenderIDResponse

      def initialize: (client: PreludeSDK::Client) -> void
    end
  end
end
