module PreludeSDK
  module Resources
    class Watch
      def feed_back: (
        feedbacks: ::Array[PreludeSDK::Models::WatchFeedBackParams::Feedback],
        ?request_options: PreludeSDK::request_opts
      ) -> PreludeSDK::Models::WatchFeedBackResponse

      def predict: (
        target: PreludeSDK::Models::WatchPredictParams::Target,
        ?dispatch_id: String,
        ?metadata: PreludeSDK::Models::WatchPredictParams::Metadata,
        ?signals: PreludeSDK::Models::WatchPredictParams::Signals,
        ?request_options: PreludeSDK::request_opts
      ) -> PreludeSDK::Models::WatchPredictResponse

      def initialize: (client: PreludeSDK::Client) -> void
    end
  end
end
