module PreludeSDK
  module Resources
    class Watch
      def predict: (
        target: PreludeSDK::Models::WatchPredictParams::Target,
        ?dispatch_id: String,
        ?metadata: PreludeSDK::Models::WatchPredictParams::Metadata,
        ?signals: PreludeSDK::Models::WatchPredictParams::Signals,
        ?request_options: PreludeSDK::request_opts
      ) -> PreludeSDK::Models::WatchPredictResponse

      def send_events: (
        events: ::Array[PreludeSDK::Models::WatchSendEventsParams::Event],
        ?request_options: PreludeSDK::request_opts
      ) -> PreludeSDK::Models::WatchSendEventsResponse

      def send_feedbacks: (
        feedbacks: ::Array[PreludeSDK::Models::WatchSendFeedbacksParams::Feedback],
        ?request_options: PreludeSDK::request_opts
      ) -> PreludeSDK::Models::WatchSendFeedbacksResponse

      def initialize: (client: PreludeSDK::Client) -> void
    end
  end
end
