module PreludeSDK
  module Resources
    class Transactional
      def send_: (
        template_id: String,
        to: String,
        ?callback_url: String,
        ?correlation_id: String,
        ?expires_at: String,
        ?from: String,
        ?locale: String,
        ?variables: ::Hash[Symbol, String],
        ?request_options: PreludeSDK::request_opts
      ) -> PreludeSDK::Models::TransactionalSendResponse

      def initialize: (client: PreludeSDK::Client) -> void
    end
  end
end
