module PreludeSDK
  class Unknown = PreludeSDK::Internal::Type::Unknown

  class BooleanModel = PreludeSDK::Internal::Type::BooleanModel

  module Enum = PreludeSDK::Internal::Type::Enum

  module Union = PreludeSDK::Internal::Type::Union

  class ArrayOf = PreludeSDK::Internal::Type::ArrayOf

  class HashOf = PreludeSDK::Internal::Type::HashOf

  class BaseModel = PreludeSDK::Internal::Type::BaseModel

  type request_parameters = PreludeSDK::Internal::Type::request_parameters

  module RequestParameters = PreludeSDK::Internal::Type::RequestParameters
end
