module PreludeSDK
  module Errors
    class Error < StandardError
      attr_accessor cause: StandardError?
    end

    class ConversionError < PreludeSDK::Errors::Error
    end

    class APIError < PreludeSDK::Errors::Error
      attr_accessor url: URI::Generic

      attr_accessor status: Integer?

      attr_accessor body: top?

      def initialize: (
        url: URI::Generic,
        ?status: Integer?,
        ?body: Object?,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APIConnectionError < PreludeSDK::Errors::APIError
      def initialize: (
        url: URI::Generic,
        ?status: nil,
        ?body: nil,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APITimeoutError < PreludeSDK::Errors::APIConnectionError
      def initialize: (
        url: URI::Generic,
        ?status: nil,
        ?body: nil,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APIStatusError < PreludeSDK::Errors::APIError
      def self.for: (
        url: URI::Generic,
        status: Integer,
        body: Object?,
        request: nil,
        response: nil,
        ?message: String?
      ) -> instance

      def initialize: (
        url: URI::Generic,
        status: Integer,
        body: Object?,
        request: nil,
        response: nil,
        ?message: String?
      ) -> void
    end

    class BadRequestError < PreludeSDK::Errors::APIStatusError
      HTTP_STATUS: 400
    end

    class AuthenticationError < PreludeSDK::Errors::APIStatusError
      HTTP_STATUS: 401
    end

    class PermissionDeniedError < PreludeSDK::Errors::APIStatusError
      HTTP_STATUS: 403
    end

    class NotFoundError < PreludeSDK::Errors::APIStatusError
      HTTP_STATUS: 404
    end

    class ConflictError < PreludeSDK::Errors::APIStatusError
      HTTP_STATUS: 409
    end

    class UnprocessableEntityError < PreludeSDK::Errors::APIStatusError
      HTTP_STATUS: 422
    end

    class RateLimitError < PreludeSDK::Errors::APIStatusError
      HTTP_STATUS: 429
    end

    class InternalServerError < PreludeSDK::Errors::APIStatusError
      HTTP_STATUS: Range[Integer]
    end
  end
end
