module PreludeSDK
  class LookupLookupParams = PreludeSDK::Models::LookupLookupParams

  class TransactionalSendParams = PreludeSDK::Models::TransactionalSendParams

  class VerificationCheckParams = PreludeSDK::Models::VerificationCheckParams

  class VerificationCreateParams = PreludeSDK::Models::VerificationCreateParams

  class VerificationManagementListSenderIDsParams = PreludeSDK::Models::VerificationManagementListSenderIDsParams

  class VerificationManagementSubmitSenderIDParams = PreludeSDK::Models::VerificationManagementSubmitSenderIDParams

  class WatchPredictParams = PreludeSDK::Models::WatchPredictParams

  class WatchSendEventsParams = PreludeSDK::Models::WatchSendEventsParams

  class WatchSendFeedbacksParams = PreludeSDK::Models::WatchSendFeedbacksParams
end
