module PreludeSDK
  class LookupLookupParams = PreludeSDK::Models::LookupLookupParams

  class NotifyGetSubscriptionConfigParams = PreludeSDK::Models::NotifyGetSubscriptionConfigParams

  class NotifyGetSubscriptionPhoneNumberParams = PreludeSDK::Models::NotifyGetSubscriptionPhoneNumberParams

  class NotifyListSubscriptionConfigsParams = PreludeSDK::Models::NotifyListSubscriptionConfigsParams

  class NotifyListSubscriptionPhoneNumberEventsParams = PreludeSDK::Models::NotifyListSubscriptionPhoneNumberEventsParams

  class NotifyListSubscriptionPhoneNumbersParams = PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersParams

  class NotifySendBatchParams = PreludeSDK::Models::NotifySendBatchParams

  class NotifySendParams = PreludeSDK::Models::NotifySendParams

  class TransactionalSendParams = PreludeSDK::Models::TransactionalSendParams

  class VerificationCheckParams = PreludeSDK::Models::VerificationCheckParams

  class VerificationCreateParams = PreludeSDK::Models::VerificationCreateParams

  class VerificationManagementDeletePhoneNumberParams = PreludeSDK::Models::VerificationManagementDeletePhoneNumberParams

  class VerificationManagementListPhoneNumbersParams = PreludeSDK::Models::VerificationManagementListPhoneNumbersParams

  class VerificationManagementListSenderIDsParams = PreludeSDK::Models::VerificationManagementListSenderIDsParams

  class VerificationManagementSetPhoneNumberParams = PreludeSDK::Models::VerificationManagementSetPhoneNumberParams

  class VerificationManagementSubmitSenderIDParams = PreludeSDK::Models::VerificationManagementSubmitSenderIDParams

  class WatchPredictParams = PreludeSDK::Models::WatchPredictParams

  class WatchSendEventsParams = PreludeSDK::Models::WatchSendEventsParams

  class WatchSendFeedbacksParams = PreludeSDK::Models::WatchSendFeedbacksParams
end
