module PreludeSDK
  module Models
    type lookup_lookup_params =
      { type: ::Array[PreludeSDK::LookupLookupParams::type_] }
      & PreludeSDK::Internal::Type::request_parameters

    class LookupLookupParams < PreludeSDK::Internal::Type::BaseModel
      extend PreludeSDK::Internal::Type::RequestParameters::Converter
      include PreludeSDK::Internal::Type::RequestParameters

      attr_reader type: ::Array[PreludeSDK::LookupLookupParams::type_]?

      def type=: (
        ::Array[PreludeSDK::LookupLookupParams::type_]
      ) -> ::Array[PreludeSDK::LookupLookupParams::type_]

      def initialize: (
        ?type: ::Array[PreludeSDK::LookupLookupParams::type_],
        ?request_options: PreludeSDK::request_opts
      ) -> void

      type type_ = :cnam

      module Type
        extend PreludeSDK::Internal::Type::Enum

        CNAM: :cnam

        def self?.values: -> ::Array[PreludeSDK::LookupLookupParams::type_]
      end
    end
  end
end
