module PreludeSDK
  module Models
    type notify_list_subscription_phone_numbers_response =
      {
        phone_numbers: ::Array[PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber],
        next_cursor: String
      }

    class NotifyListSubscriptionPhoneNumbersResponse < PreludeSDK::Internal::Type::BaseModel
      attr_accessor phone_numbers: ::Array[PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber]

      attr_reader next_cursor: String?

      def next_cursor=: (String) -> String

      def initialize: (
        phone_numbers: ::Array[PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber],
        ?next_cursor: String
      ) -> void

      def to_hash: -> {
        phone_numbers: ::Array[PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber],
        next_cursor: String
      }

      type phone_number =
        {
          config_id: String,
          phone_number: String,
          source: PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber::source,
          state: PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber::state,
          updated_at: Time,
          reason: String
        }

      class PhoneNumber < PreludeSDK::Internal::Type::BaseModel
        attr_accessor config_id: String

        attr_accessor phone_number: String

        attr_accessor source: PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber::source

        attr_accessor state: PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber::state

        attr_accessor updated_at: Time

        attr_reader reason: String?

        def reason=: (String) -> String

        def initialize: (
          config_id: String,
          phone_number: String,
          source: PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber::source,
          state: PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber::state,
          updated_at: Time,
          ?reason: String
        ) -> void

        def to_hash: -> {
          config_id: String,
          phone_number: String,
          source: PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber::source,
          state: PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber::state,
          updated_at: Time,
          reason: String
        }

        type source = :MO_KEYWORD | :API | :CSV_IMPORT | :CARRIER_DISCONNECT

        module Source
          extend PreludeSDK::Internal::Type::Enum

          MO_KEYWORD: :MO_KEYWORD
          API: :API
          CSV_IMPORT: :CSV_IMPORT
          CARRIER_DISCONNECT: :CARRIER_DISCONNECT

          def self?.values: -> ::Array[PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber::source]
        end

        type state = :SUB | :UNSUB

        module State
          extend PreludeSDK::Internal::Type::Enum

          SUB: :SUB
          UNSUB: :UNSUB

          def self?.values: -> ::Array[PreludeSDK::Models::NotifyListSubscriptionPhoneNumbersResponse::PhoneNumber::state]
        end
      end
    end
  end
end
