module PreludeSDK
  module Models
    type notify_send_response =
      {
        id: String,
        created_at: Time,
        expires_at: Time,
        template_id: String,
        to: String,
        variables: ::Hash[Symbol, String],
        callback_url: String,
        correlation_id: String,
        encoding: PreludeSDK::Models::NotifySendResponse::encoding,
        estimated_segment_count: Integer,
        from: String,
        schedule_at: Time
      }

    class NotifySendResponse < PreludeSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor expires_at: Time

      attr_accessor template_id: String

      attr_accessor to: String

      attr_accessor variables: ::Hash[Symbol, String]

      attr_reader callback_url: String?

      def callback_url=: (String) -> String

      attr_reader correlation_id: String?

      def correlation_id=: (String) -> String

      attr_reader encoding: PreludeSDK::Models::NotifySendResponse::encoding?

      def encoding=: (
        PreludeSDK::Models::NotifySendResponse::encoding
      ) -> PreludeSDK::Models::NotifySendResponse::encoding

      attr_reader estimated_segment_count: Integer?

      def estimated_segment_count=: (Integer) -> Integer

      attr_reader from: String?

      def from=: (String) -> String

      attr_reader schedule_at: Time?

      def schedule_at=: (Time) -> Time

      def initialize: (
        id: String,
        created_at: Time,
        expires_at: Time,
        template_id: String,
        to: String,
        variables: ::Hash[Symbol, String],
        ?callback_url: String,
        ?correlation_id: String,
        ?encoding: PreludeSDK::Models::NotifySendResponse::encoding,
        ?estimated_segment_count: Integer,
        ?from: String,
        ?schedule_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        expires_at: Time,
        template_id: String,
        to: String,
        variables: ::Hash[Symbol, String],
        callback_url: String,
        correlation_id: String,
        encoding: PreludeSDK::Models::NotifySendResponse::encoding,
        estimated_segment_count: Integer,
        from: String,
        schedule_at: Time
      }

      type encoding = :"GSM-7" | :"UCS-2"

      module Encoding
        extend PreludeSDK::Internal::Type::Enum

        GSM_7: :"GSM-7"
        UCS_2: :"UCS-2"

        def self?.values: -> ::Array[PreludeSDK::Models::NotifySendResponse::encoding]
      end
    end
  end
end
