module PreludeSDK
  module Models
    type notify_send_params =
      {
        template_id: String,
        to: String,
        callback_url: String,
        context: PreludeSDK::NotifySendParams::Context,
        correlation_id: String,
        document: PreludeSDK::NotifySendParams::Document,
        expires_at: Time,
        from: String,
        locale: String,
        preferred_channel: PreludeSDK::Models::NotifySendParams::preferred_channel,
        schedule_at: Time,
        text: String,
        variables: ::Hash[Symbol, String]
      }
      & PreludeSDK::Internal::Type::request_parameters

    class NotifySendParams < PreludeSDK::Internal::Type::BaseModel
      extend PreludeSDK::Internal::Type::RequestParameters::Converter
      include PreludeSDK::Internal::Type::RequestParameters

      attr_accessor template_id: String

      attr_accessor to: String

      attr_reader callback_url: String?

      def callback_url=: (String) -> String

      attr_reader context: PreludeSDK::NotifySendParams::Context?

      def context=: (
        PreludeSDK::NotifySendParams::Context
      ) -> PreludeSDK::NotifySendParams::Context

      attr_reader correlation_id: String?

      def correlation_id=: (String) -> String

      attr_reader document: PreludeSDK::NotifySendParams::Document?

      def document=: (
        PreludeSDK::NotifySendParams::Document
      ) -> PreludeSDK::NotifySendParams::Document

      attr_reader expires_at: Time?

      def expires_at=: (Time) -> Time

      attr_reader from: String?

      def from=: (String) -> String

      attr_reader locale: String?

      def locale=: (String) -> String

      attr_reader preferred_channel: PreludeSDK::Models::NotifySendParams::preferred_channel?

      def preferred_channel=: (
        PreludeSDK::Models::NotifySendParams::preferred_channel
      ) -> PreludeSDK::Models::NotifySendParams::preferred_channel

      attr_reader schedule_at: Time?

      def schedule_at=: (Time) -> Time

      attr_reader text: String?

      def text=: (String) -> String

      attr_reader variables: ::Hash[Symbol, String]?

      def variables=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      def initialize: (
        template_id: String,
        to: String,
        ?callback_url: String,
        ?context: PreludeSDK::NotifySendParams::Context,
        ?correlation_id: String,
        ?document: PreludeSDK::NotifySendParams::Document,
        ?expires_at: Time,
        ?from: String,
        ?locale: String,
        ?preferred_channel: PreludeSDK::Models::NotifySendParams::preferred_channel,
        ?schedule_at: Time,
        ?text: String,
        ?variables: ::Hash[Symbol, String],
        ?request_options: PreludeSDK::request_opts
      ) -> void

      def to_hash: -> {
        template_id: String,
        to: String,
        callback_url: String,
        context: PreludeSDK::NotifySendParams::Context,
        correlation_id: String,
        document: PreludeSDK::NotifySendParams::Document,
        expires_at: Time,
        from: String,
        locale: String,
        preferred_channel: PreludeSDK::Models::NotifySendParams::preferred_channel,
        schedule_at: Time,
        text: String,
        variables: ::Hash[Symbol, String],
        request_options: PreludeSDK::RequestOptions
      }

      type context = { reply_to: String }

      class Context < PreludeSDK::Internal::Type::BaseModel
        attr_accessor reply_to: String

        def initialize: (reply_to: String) -> void

        def to_hash: -> { reply_to: String }
      end

      type document = { url: String, filename: String }

      class Document < PreludeSDK::Internal::Type::BaseModel
        attr_accessor url: String

        attr_reader filename: String?

        def filename=: (String) -> String

        def initialize: (url: String, ?filename: String) -> void

        def to_hash: -> { url: String, filename: String }
      end

      type preferred_channel = :sms | :rcs | :whatsapp

      module PreferredChannel
        extend PreludeSDK::Internal::Type::Enum

        SMS: :sms
        RCS: :rcs
        WHATSAPP: :whatsapp

        def self?.values: -> ::Array[PreludeSDK::Models::NotifySendParams::preferred_channel]
      end
    end
  end
end
