module PreludeSDK
  module Models
    type transactional_send_response =
      {
        id: String,
        created_at: Time,
        expires_at: Time,
        template_id: String,
        to: String,
        variables: ::Hash[Symbol, String],
        callback_url: String,
        correlation_id: String,
        from: String
      }

    class TransactionalSendResponse < PreludeSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor expires_at: Time

      attr_accessor template_id: String

      attr_accessor to: String

      attr_accessor variables: ::Hash[Symbol, String]

      attr_reader callback_url: String?

      def callback_url=: (String) -> String

      attr_reader correlation_id: String?

      def correlation_id=: (String) -> String

      attr_reader from: String?

      def from=: (String) -> String

      def initialize: (
        id: String,
        created_at: Time,
        expires_at: Time,
        template_id: String,
        to: String,
        variables: ::Hash[Symbol, String],
        ?callback_url: String,
        ?correlation_id: String,
        ?from: String
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        expires_at: Time,
        template_id: String,
        to: String,
        variables: ::Hash[Symbol, String],
        callback_url: String,
        correlation_id: String,
        from: String
      }
    end
  end
end
