module PreludeSDK
  module Models
    type verification_management_list_phone_numbers_response =
      {
        phone_numbers: ::Array[PreludeSDK::Models::VerificationManagementListPhoneNumbersResponse::PhoneNumber]
      }

    class VerificationManagementListPhoneNumbersResponse < PreludeSDK::Internal::Type::BaseModel
      attr_accessor phone_numbers: ::Array[PreludeSDK::Models::VerificationManagementListPhoneNumbersResponse::PhoneNumber]

      def initialize: (
        phone_numbers: ::Array[PreludeSDK::Models::VerificationManagementListPhoneNumbersResponse::PhoneNumber]
      ) -> void

      def to_hash: -> {
        phone_numbers: ::Array[PreludeSDK::Models::VerificationManagementListPhoneNumbersResponse::PhoneNumber]
      }

      type phone_number = { created_at: Time, phone_number: String }

      class PhoneNumber < PreludeSDK::Internal::Type::BaseModel
        attr_accessor created_at: Time

        attr_accessor phone_number: String

        def initialize: (created_at: Time, phone_number: String) -> void

        def to_hash: -> { created_at: Time, phone_number: String }
      end
    end
  end
end
