module PreludeSDK
  module Models
    type verification_check_response =
      {
        status: PreludeSDK::Models::VerificationCheckResponse::status,
        id: String,
        metadata: PreludeSDK::Models::VerificationCheckResponse::Metadata,
        request_id: String
      }

    class VerificationCheckResponse < PreludeSDK::Internal::Type::BaseModel
      attr_accessor status: PreludeSDK::Models::VerificationCheckResponse::status

      attr_reader id: String?

      def id=: (String) -> String

      attr_reader metadata: PreludeSDK::Models::VerificationCheckResponse::Metadata?

      def metadata=: (
        PreludeSDK::Models::VerificationCheckResponse::Metadata
      ) -> PreludeSDK::Models::VerificationCheckResponse::Metadata

      attr_reader request_id: String?

      def request_id=: (String) -> String

      def initialize: (
        status: PreludeSDK::Models::VerificationCheckResponse::status,
        ?id: String,
        ?metadata: PreludeSDK::Models::VerificationCheckResponse::Metadata,
        ?request_id: String
      ) -> void

      def to_hash: -> PreludeSDK::Models::verification_check_response

      type status = :success | :failure | :expired_or_not_found

      module Status
        extend PreludeSDK::Internal::Type::Enum

        SUCCESS: :success
        FAILURE: :failure
        EXPIRED_OR_NOT_FOUND: :expired_or_not_found

        def self?.values: -> ::Array[PreludeSDK::Models::VerificationCheckResponse::status]
      end

      type metadata = { correlation_id: String }

      class Metadata < PreludeSDK::Internal::Type::BaseModel
        attr_reader correlation_id: String?

        def correlation_id=: (String) -> String

        def initialize: (?correlation_id: String) -> void

        def to_hash: -> PreludeSDK::Models::VerificationCheckResponse::metadata
      end
    end
  end
end
