module PreludeSDK
  module Models
    type verification_management_list_sender_ids_response_item =
      {
        status: PreludeSDK::Models::VerificationManagementListSenderIDsResponseItem::status,
        value: String
      }

    class VerificationManagementListSenderIDsResponseItem < PreludeSDK::Internal::Type::BaseModel
      attr_reader status: PreludeSDK::Models::VerificationManagementListSenderIDsResponseItem::status?

      def status=: (
        PreludeSDK::Models::VerificationManagementListSenderIDsResponseItem::status
      ) -> PreludeSDK::Models::VerificationManagementListSenderIDsResponseItem::status

      attr_reader value: String?

      def value=: (String) -> String

      def initialize: (
        ?status: PreludeSDK::Models::VerificationManagementListSenderIDsResponseItem::status,
        ?value: String
      ) -> void

      def to_hash: -> {
        status: PreludeSDK::Models::VerificationManagementListSenderIDsResponseItem::status,
        value: String
      }

      type status = :approved | :pending | :rejected

      module Status
        extend PreludeSDK::Internal::Type::Enum

        APPROVED: :approved
        PENDING: :pending
        REJECTED: :rejected

        def self?.values: -> ::Array[PreludeSDK::Models::VerificationManagementListSenderIDsResponseItem::status]
      end
    end

    type verification_management_list_sender_ids_response =
      ::Array[PreludeSDK::Models::VerificationManagementListSenderIDsResponseItem]

    VerificationManagementListSenderIDsResponse: PreludeSDK::Internal::Type::Converter
  end
end
