module PreludeSDK
  module Models
    type verification_management_set_phone_number_params =
      {
        action: PreludeSDK::Models::VerificationManagementSetPhoneNumberParams::action,
        phone_number: String
      }
      & PreludeSDK::Internal::Type::request_parameters

    class VerificationManagementSetPhoneNumberParams < PreludeSDK::Internal::Type::BaseModel
      extend PreludeSDK::Internal::Type::RequestParameters::Converter
      include PreludeSDK::Internal::Type::RequestParameters

      attr_accessor action: PreludeSDK::Models::VerificationManagementSetPhoneNumberParams::action

      attr_accessor phone_number: String

      def initialize: (
        action: PreludeSDK::Models::VerificationManagementSetPhoneNumberParams::action,
        phone_number: String,
        ?request_options: PreludeSDK::request_opts
      ) -> void

      def to_hash: -> {
        action: PreludeSDK::Models::VerificationManagementSetPhoneNumberParams::action,
        phone_number: String,
        request_options: PreludeSDK::RequestOptions
      }

      type action = :allow | :block

      module Action
        extend PreludeSDK::Internal::Type::Enum

        ALLOW: :allow
        BLOCK: :block

        def self?.values: -> ::Array[PreludeSDK::Models::VerificationManagementSetPhoneNumberParams::action]
      end
    end
  end
end
