module PreludeSDK
  module Models
    type watch_send_feedbacks_params =
      { feedbacks: ::Array[PreludeSDK::WatchSendFeedbacksParams::Feedback] }
      & PreludeSDK::Internal::Type::request_parameters

    class WatchSendFeedbacksParams < PreludeSDK::Internal::Type::BaseModel
      extend PreludeSDK::Internal::Type::RequestParameters::Converter
      include PreludeSDK::Internal::Type::RequestParameters

      attr_accessor feedbacks: ::Array[PreludeSDK::WatchSendFeedbacksParams::Feedback]

      def initialize: (
        feedbacks: ::Array[PreludeSDK::WatchSendFeedbacksParams::Feedback],
        ?request_options: PreludeSDK::request_opts
      ) -> void

      def to_hash: -> {
        feedbacks: ::Array[PreludeSDK::WatchSendFeedbacksParams::Feedback],
        request_options: PreludeSDK::RequestOptions
      }

      type feedback =
        {
          target: PreludeSDK::WatchSendFeedbacksParams::Feedback::Target,
          type: PreludeSDK::Models::WatchSendFeedbacksParams::Feedback::type_,
          metadata: PreludeSDK::WatchSendFeedbacksParams::Feedback::Metadata
        }

      class Feedback < PreludeSDK::Internal::Type::BaseModel
        attr_accessor target: PreludeSDK::WatchSendFeedbacksParams::Feedback::Target

        attr_accessor type: PreludeSDK::Models::WatchSendFeedbacksParams::Feedback::type_

        attr_reader metadata: PreludeSDK::WatchSendFeedbacksParams::Feedback::Metadata?

        def metadata=: (
          PreludeSDK::WatchSendFeedbacksParams::Feedback::Metadata
        ) -> PreludeSDK::WatchSendFeedbacksParams::Feedback::Metadata

        def initialize: (
          target: PreludeSDK::WatchSendFeedbacksParams::Feedback::Target,
          type: PreludeSDK::Models::WatchSendFeedbacksParams::Feedback::type_,
          ?metadata: PreludeSDK::WatchSendFeedbacksParams::Feedback::Metadata
        ) -> void

        def to_hash: -> {
          target: PreludeSDK::WatchSendFeedbacksParams::Feedback::Target,
          type: PreludeSDK::Models::WatchSendFeedbacksParams::Feedback::type_,
          metadata: PreludeSDK::WatchSendFeedbacksParams::Feedback::Metadata
        }

        type target =
          {
            type: PreludeSDK::Models::WatchSendFeedbacksParams::Feedback::Target::type_,
            value: String
          }

        class Target < PreludeSDK::Internal::Type::BaseModel
          attr_accessor type: PreludeSDK::Models::WatchSendFeedbacksParams::Feedback::Target::type_

          attr_accessor value: String

          def initialize: (
            type: PreludeSDK::Models::WatchSendFeedbacksParams::Feedback::Target::type_,
            value: String
          ) -> void

          def to_hash: -> {
            type: PreludeSDK::Models::WatchSendFeedbacksParams::Feedback::Target::type_,
            value: String
          }

          type type_ = :phone_number | :email_address

          module Type
            extend PreludeSDK::Internal::Type::Enum

            PHONE_NUMBER: :phone_number
            EMAIL_ADDRESS: :email_address

            def self?.values: -> ::Array[PreludeSDK::Models::WatchSendFeedbacksParams::Feedback::Target::type_]
          end
        end

        type type_ = :"verification.started" | :"verification.completed"

        module Type
          extend PreludeSDK::Internal::Type::Enum

          VERIFICATION_STARTED: :"verification.started"
          VERIFICATION_COMPLETED: :"verification.completed"

          def self?.values: -> ::Array[PreludeSDK::Models::WatchSendFeedbacksParams::Feedback::type_]
        end

        type metadata = { correlation_id: String }

        class Metadata < PreludeSDK::Internal::Type::BaseModel
          attr_reader correlation_id: String?

          def correlation_id=: (String) -> String

          def initialize: (?correlation_id: String) -> void

          def to_hash: -> { correlation_id: String }
        end
      end
    end
  end
end
