module PreludeSDK
  module Models
    type watch_predict_params =
      {
        target: PreludeSDK::Target,
        dispatch_id: String,
        metadata: PreludeSDK::WatchPredictParams::Metadata,
        signals: PreludeSDK::Signals
      }
      & PreludeSDK::Internal::Type::request_parameters

    class WatchPredictParams < PreludeSDK::Internal::Type::BaseModel
      extend PreludeSDK::Internal::Type::RequestParameters::Converter
      include PreludeSDK::Internal::Type::RequestParameters

      attr_accessor target: PreludeSDK::Target

      attr_reader dispatch_id: String?

      def dispatch_id=: (String) -> String

      attr_reader metadata: PreludeSDK::WatchPredictParams::Metadata?

      def metadata=: (
        PreludeSDK::WatchPredictParams::Metadata
      ) -> PreludeSDK::WatchPredictParams::Metadata

      attr_reader signals: PreludeSDK::Signals?

      def signals=: (PreludeSDK::Signals) -> PreludeSDK::Signals

      def initialize: (
        target: PreludeSDK::Target,
        ?dispatch_id: String,
        ?metadata: PreludeSDK::WatchPredictParams::Metadata,
        ?signals: PreludeSDK::Signals,
        ?request_options: PreludeSDK::request_opts
      ) -> void

      def to_hash: -> {
        target: PreludeSDK::Target,
        dispatch_id: String,
        metadata: PreludeSDK::WatchPredictParams::Metadata,
        signals: PreludeSDK::Signals,
        request_options: PreludeSDK::RequestOptions
      }

      type metadata = { correlation_id: String }

      class Metadata < PreludeSDK::Internal::Type::BaseModel
        attr_reader correlation_id: String?

        def correlation_id=: (String) -> String

        def initialize: (?correlation_id: String) -> void

        def to_hash: -> { correlation_id: String }
      end
    end
  end
end
