module PreludeSDK
  module Models
    type watch_feed_back_response = { id: String }

    class WatchFeedBackResponse < PreludeSDK::Internal::Type::BaseModel
      attr_accessor id: String

      def initialize: (id: String) -> void

      def to_hash: -> PreludeSDK::Models::watch_feed_back_response
    end
  end
end
