module PreludeSDK
  module Models
    type watch_predict_response =
      {
        id: String,
        prediction: PreludeSDK::Models::WatchPredictResponse::prediction,
        request_id: String,
        risk_factors: ::Array[PreludeSDK::Models::WatchPredictResponse::risk_factor]
      }

    class WatchPredictResponse < PreludeSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor prediction: PreludeSDK::Models::WatchPredictResponse::prediction

      attr_accessor request_id: String

      attr_reader risk_factors: ::Array[PreludeSDK::Models::WatchPredictResponse::risk_factor]?

      def risk_factors=: (
        ::Array[PreludeSDK::Models::WatchPredictResponse::risk_factor]
      ) -> ::Array[PreludeSDK::Models::WatchPredictResponse::risk_factor]

      def initialize: (
        id: String,
        prediction: PreludeSDK::Models::WatchPredictResponse::prediction,
        request_id: String,
        ?risk_factors: ::Array[PreludeSDK::Models::WatchPredictResponse::risk_factor]
      ) -> void

      def to_hash: -> {
        id: String,
        prediction: PreludeSDK::Models::WatchPredictResponse::prediction,
        request_id: String,
        risk_factors: ::Array[PreludeSDK::Models::WatchPredictResponse::risk_factor]
      }

      type prediction = :legitimate | :suspicious

      module Prediction
        extend PreludeSDK::Internal::Type::Enum

        LEGITIMATE: :legitimate
        SUSPICIOUS: :suspicious

        def self?.values: -> ::Array[PreludeSDK::Models::WatchPredictResponse::prediction]
      end

      type risk_factor =
        :account_risk_profile
        | :automation_signature
        | :carrier_not_permitted
        | :client_fingerprint_mismatch
        | :custom_policy
        | :device_emulator
        | :device_not_permitted
        | :device_reuse
        | :expired_signals
        | :fraud_database
        | :invalid_signature
        | :ip_concentration
        | :ip_reputation
        | :location_mismatch
        | :missing_signals
        | :number_range_abuse
        | :poor_conversion_history
        | :proxy_network
        | :repeated_attempts
        | :temporary_phone_number

      module RiskFactor
        extend PreludeSDK::Internal::Type::Enum

        ACCOUNT_RISK_PROFILE: :account_risk_profile
        AUTOMATION_SIGNATURE: :automation_signature
        CARRIER_NOT_PERMITTED: :carrier_not_permitted
        CLIENT_FINGERPRINT_MISMATCH: :client_fingerprint_mismatch
        CUSTOM_POLICY: :custom_policy
        DEVICE_EMULATOR: :device_emulator
        DEVICE_NOT_PERMITTED: :device_not_permitted
        DEVICE_REUSE: :device_reuse
        EXPIRED_SIGNALS: :expired_signals
        FRAUD_DATABASE: :fraud_database
        INVALID_SIGNATURE: :invalid_signature
        IP_CONCENTRATION: :ip_concentration
        IP_REPUTATION: :ip_reputation
        LOCATION_MISMATCH: :location_mismatch
        MISSING_SIGNALS: :missing_signals
        NUMBER_RANGE_ABUSE: :number_range_abuse
        POOR_CONVERSION_HISTORY: :poor_conversion_history
        PROXY_NETWORK: :proxy_network
        REPEATED_ATTEMPTS: :repeated_attempts
        TEMPORARY_PHONE_NUMBER: :temporary_phone_number

        def self?.values: -> ::Array[PreludeSDK::Models::WatchPredictResponse::risk_factor]
      end
    end
  end
end
