module PreludeSDK
  module Models
    type watch_send_feedbacks_response =
      {
        request_id: String,
        status: PreludeSDK::Models::WatchSendFeedbacksResponse::status
      }

    class WatchSendFeedbacksResponse < PreludeSDK::Internal::Type::BaseModel
      attr_accessor request_id: String

      attr_accessor status: PreludeSDK::Models::WatchSendFeedbacksResponse::status

      def initialize: (
        request_id: String,
        status: PreludeSDK::Models::WatchSendFeedbacksResponse::status
      ) -> void

      def to_hash: -> {
        request_id: String,
        status: PreludeSDK::Models::WatchSendFeedbacksResponse::status
      }

      type status = :success

      module Status
        extend PreludeSDK::Internal::Type::Enum

        SUCCESS: :success

        def self?.values: -> ::Array[PreludeSDK::Models::WatchSendFeedbacksResponse::status]
      end
    end
  end
end
