module PreludeSDK
  module Models
    type verification_create_response =
      {
        id: String,
        metadata: PreludeSDK::Models::VerificationCreateResponse::Metadata,
        method_: PreludeSDK::Models::VerificationCreateResponse::method_,
        request_id: String,
        status: PreludeSDK::Models::VerificationCreateResponse::status
      }

    class VerificationCreateResponse < PreludeSDK::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader metadata: PreludeSDK::Models::VerificationCreateResponse::Metadata?

      def metadata=: (
        PreludeSDK::Models::VerificationCreateResponse::Metadata
      ) -> PreludeSDK::Models::VerificationCreateResponse::Metadata

      attr_reader method_: PreludeSDK::Models::VerificationCreateResponse::method_?

      def method_=: (
        PreludeSDK::Models::VerificationCreateResponse::method_
      ) -> PreludeSDK::Models::VerificationCreateResponse::method_

      attr_reader request_id: String?

      def request_id=: (String) -> String

      attr_reader status: PreludeSDK::Models::VerificationCreateResponse::status?

      def status=: (
        PreludeSDK::Models::VerificationCreateResponse::status
      ) -> PreludeSDK::Models::VerificationCreateResponse::status

      def initialize:
        (
          id: String,
          metadata: PreludeSDK::Models::VerificationCreateResponse::Metadata,
          method_: PreludeSDK::Models::VerificationCreateResponse::method_,
          request_id: String,
          status: PreludeSDK::Models::VerificationCreateResponse::status
        ) -> void
        | (
          ?PreludeSDK::Models::verification_create_response
          | PreludeSDK::BaseModel data
        ) -> void

      def to_hash: -> PreludeSDK::Models::verification_create_response

      type metadata = { correlation_id: String }

      class Metadata < PreludeSDK::BaseModel
        attr_reader correlation_id: String?

        def correlation_id=: (String) -> String

        def initialize:
          (correlation_id: String) -> void
          | (
            ?PreludeSDK::Models::VerificationCreateResponse::metadata
            | PreludeSDK::BaseModel data
          ) -> void

        def to_hash: -> PreludeSDK::Models::VerificationCreateResponse::metadata
      end

      type method_ = :message

      class Method < PreludeSDK::Enum
        MESSAGE: :message

        def self.values: -> ::Array[PreludeSDK::Models::VerificationCreateResponse::method_]
      end

      type status = :success | :retry | :blocked

      class Status < PreludeSDK::Enum
        SUCCESS: :success
        RETRY: :retry
        BLOCKED: :blocked

        def self.values: -> ::Array[PreludeSDK::Models::VerificationCreateResponse::status]
      end
    end
  end
end
