module PreludeSDK
  module Models
    type verification_create_params =
      {
        target: PreludeSDK::Models::VerificationCreateParams::Target,
        dispatch_id: String,
        metadata: PreludeSDK::Models::VerificationCreateParams::Metadata,
        options: PreludeSDK::Models::VerificationCreateParams::Options,
        signals: PreludeSDK::Models::VerificationCreateParams::Signals
      }
      & PreludeSDK::request_parameters

    class VerificationCreateParams < PreludeSDK::BaseModel
      extend PreludeSDK::RequestParameters::Converter
      include PreludeSDK::RequestParameters

      attr_accessor target: PreludeSDK::Models::VerificationCreateParams::Target

      attr_reader dispatch_id: String?

      def dispatch_id=: (String) -> String

      attr_reader metadata: PreludeSDK::Models::VerificationCreateParams::Metadata?

      def metadata=: (
        PreludeSDK::Models::VerificationCreateParams::Metadata
      ) -> PreludeSDK::Models::VerificationCreateParams::Metadata

      attr_reader options: PreludeSDK::Models::VerificationCreateParams::Options?

      def options=: (
        PreludeSDK::Models::VerificationCreateParams::Options
      ) -> PreludeSDK::Models::VerificationCreateParams::Options

      attr_reader signals: PreludeSDK::Models::VerificationCreateParams::Signals?

      def signals=: (
        PreludeSDK::Models::VerificationCreateParams::Signals
      ) -> PreludeSDK::Models::VerificationCreateParams::Signals

      def initialize: (
        target: PreludeSDK::Models::VerificationCreateParams::Target,
        ?dispatch_id: String,
        ?metadata: PreludeSDK::Models::VerificationCreateParams::Metadata,
        ?options: PreludeSDK::Models::VerificationCreateParams::Options,
        ?signals: PreludeSDK::Models::VerificationCreateParams::Signals,
        ?request_options: PreludeSDK::request_opts
      ) -> void

      def to_hash: -> PreludeSDK::Models::verification_create_params

      type target =
        {
          type: PreludeSDK::Models::VerificationCreateParams::Target::type_,
          value: String
        }

      class Target < PreludeSDK::BaseModel
        attr_accessor type: PreludeSDK::Models::VerificationCreateParams::Target::type_

        attr_accessor value: String

        def initialize: (
          type: PreludeSDK::Models::VerificationCreateParams::Target::type_,
          value: String
        ) -> void

        def to_hash: -> PreludeSDK::Models::VerificationCreateParams::target

        type type_ = :phone_number | :email_address

        module Type
          extend PreludeSDK::Enum

          PHONE_NUMBER: :phone_number
          EMAIL_ADDRESS: :email_address

          def self?.values: -> ::Array[PreludeSDK::Models::VerificationCreateParams::Target::type_]
        end
      end

      type metadata = { correlation_id: String }

      class Metadata < PreludeSDK::BaseModel
        attr_reader correlation_id: String?

        def correlation_id=: (String) -> String

        def initialize: (?correlation_id: String) -> void

        def to_hash: -> PreludeSDK::Models::VerificationCreateParams::metadata
      end

      type options =
        {
          app_realm: PreludeSDK::Models::VerificationCreateParams::Options::AppRealm,
          callback_url: String,
          code_size: Integer,
          custom_code: String,
          locale: String,
          sender_id: String,
          template_id: String,
          variables: ::Hash[Symbol, String]
        }

      class Options < PreludeSDK::BaseModel
        attr_reader app_realm: PreludeSDK::Models::VerificationCreateParams::Options::AppRealm?

        def app_realm=: (
          PreludeSDK::Models::VerificationCreateParams::Options::AppRealm
        ) -> PreludeSDK::Models::VerificationCreateParams::Options::AppRealm

        attr_reader callback_url: String?

        def callback_url=: (String) -> String

        attr_reader code_size: Integer?

        def code_size=: (Integer) -> Integer

        attr_reader custom_code: String?

        def custom_code=: (String) -> String

        attr_reader locale: String?

        def locale=: (String) -> String

        attr_reader sender_id: String?

        def sender_id=: (String) -> String

        attr_reader template_id: String?

        def template_id=: (String) -> String

        attr_reader variables: ::Hash[Symbol, String]?

        def variables=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        def initialize: (
          ?app_realm: PreludeSDK::Models::VerificationCreateParams::Options::AppRealm,
          ?callback_url: String,
          ?code_size: Integer,
          ?custom_code: String,
          ?locale: String,
          ?sender_id: String,
          ?template_id: String,
          ?variables: ::Hash[Symbol, String]
        ) -> void

        def to_hash: -> PreludeSDK::Models::VerificationCreateParams::options

        type app_realm =
          {
            platform: PreludeSDK::Models::VerificationCreateParams::Options::AppRealm::platform,
            value: String
          }

        class AppRealm < PreludeSDK::BaseModel
          attr_accessor platform: PreludeSDK::Models::VerificationCreateParams::Options::AppRealm::platform

          attr_accessor value: String

          def initialize: (
            platform: PreludeSDK::Models::VerificationCreateParams::Options::AppRealm::platform,
            value: String
          ) -> void

          def to_hash: -> PreludeSDK::Models::VerificationCreateParams::Options::app_realm

          type platform = :android

          module Platform
            extend PreludeSDK::Enum

            ANDROID: :android

            def self?.values: -> ::Array[PreludeSDK::Models::VerificationCreateParams::Options::AppRealm::platform]
          end
        end
      end

      type signals =
        {
          app_version: String,
          device_id: String,
          device_model: String,
          device_platform: PreludeSDK::Models::VerificationCreateParams::Signals::device_platform,
          ip: String,
          is_trusted_user: bool,
          os_version: String,
          user_agent: String
        }

      class Signals < PreludeSDK::BaseModel
        attr_reader app_version: String?

        def app_version=: (String) -> String

        attr_reader device_id: String?

        def device_id=: (String) -> String

        attr_reader device_model: String?

        def device_model=: (String) -> String

        attr_reader device_platform: PreludeSDK::Models::VerificationCreateParams::Signals::device_platform?

        def device_platform=: (
          PreludeSDK::Models::VerificationCreateParams::Signals::device_platform
        ) -> PreludeSDK::Models::VerificationCreateParams::Signals::device_platform

        attr_reader ip: String?

        def ip=: (String) -> String

        attr_reader is_trusted_user: bool?

        def is_trusted_user=: (bool) -> bool

        attr_reader os_version: String?

        def os_version=: (String) -> String

        attr_reader user_agent: String?

        def user_agent=: (String) -> String

        def initialize: (
          ?app_version: String,
          ?device_id: String,
          ?device_model: String,
          ?device_platform: PreludeSDK::Models::VerificationCreateParams::Signals::device_platform,
          ?ip: String,
          ?is_trusted_user: bool,
          ?os_version: String,
          ?user_agent: String
        ) -> void

        def to_hash: -> PreludeSDK::Models::VerificationCreateParams::signals

        type device_platform = :android | :ios | :ipados | :tvos | :web

        module DevicePlatform
          extend PreludeSDK::Enum

          ANDROID: :android
          IOS: :ios
          IPADOS: :ipados
          TVOS: :tvos
          WEB: :web

          def self?.values: -> ::Array[PreludeSDK::Models::VerificationCreateParams::Signals::device_platform]
        end
      end
    end
  end
end
