module PreludeSDK
  module Models
    type watch_predict_response =
      {
        id: String,
        prediction: PreludeSDK::Models::WatchPredictResponse::prediction,
        reasoning: PreludeSDK::Models::WatchPredictResponse::Reasoning
      }

    class WatchPredictResponse < PreludeSDK::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader prediction: PreludeSDK::Models::WatchPredictResponse::prediction?

      def prediction=: (
        PreludeSDK::Models::WatchPredictResponse::prediction
      ) -> PreludeSDK::Models::WatchPredictResponse::prediction

      attr_reader reasoning: PreludeSDK::Models::WatchPredictResponse::Reasoning?

      def reasoning=: (
        PreludeSDK::Models::WatchPredictResponse::Reasoning
      ) -> PreludeSDK::Models::WatchPredictResponse::Reasoning

      def initialize:
        (
          id: String,
          prediction: PreludeSDK::Models::WatchPredictResponse::prediction,
          reasoning: PreludeSDK::Models::WatchPredictResponse::Reasoning
        ) -> void
        | (
          ?PreludeSDK::Models::watch_predict_response
          | PreludeSDK::BaseModel data
        ) -> void

      def to_hash: -> PreludeSDK::Models::watch_predict_response

      type prediction = :allow | :block

      class Prediction < PreludeSDK::Enum
        ALLOW: :allow
        BLOCK: :block

        def self.values: -> ::Array[PreludeSDK::Models::WatchPredictResponse::prediction]
      end

      type reasoning =
        {
          cause: PreludeSDK::Models::WatchPredictResponse::Reasoning::cause,
          score: Float
        }

      class Reasoning < PreludeSDK::BaseModel
        attr_reader cause: PreludeSDK::Models::WatchPredictResponse::Reasoning::cause?

        def cause=: (
          PreludeSDK::Models::WatchPredictResponse::Reasoning::cause
        ) -> PreludeSDK::Models::WatchPredictResponse::Reasoning::cause

        attr_reader score: Float?

        def score=: (Float) -> Float

        def initialize:
          (
            cause: PreludeSDK::Models::WatchPredictResponse::Reasoning::cause,
            score: Float
          ) -> void
          | (
            ?PreludeSDK::Models::WatchPredictResponse::reasoning
            | PreludeSDK::BaseModel data
          ) -> void

        def to_hash: -> PreludeSDK::Models::WatchPredictResponse::reasoning

        type cause = :none | :smart_antifraud | :repeat_number | :invalid_line

        class Cause < PreludeSDK::Enum
          NONE: :none
          SMART_ANTIFRAUD: :smart_antifraud
          REPEAT_NUMBER: :repeat_number
          INVALID_LINE: :invalid_line

          def self.values: -> ::Array[PreludeSDK::Models::WatchPredictResponse::Reasoning::cause]
        end
      end
    end
  end
end
